### ISSUE TITLE
Image Cropping

### ISSUE THREAD

**Issue by Zylinderstumpf** [Fiech/surf3tikz#5]
Looking at a surf plot from view(0,0) (side-view) covering not the whole z-axis, the exported image is cropped to the maximum y-axis value, leading to wrongly scaled image in the final tikz graphic.

Used code:
```
h_plotfig = figure(44)
some plot command generating surf plot
axis([2 5 -1 1])
zlim([-130 -80])
caxis([-120 -80])
view(0,0)
surf3tikz(h_plotfig,'PlotName')
```

Generated Code:
```
\begin{tikzpicture}
	 \begin{axis}[
	 	 grid,
	 	 enlargelimits = false,
	 	 xmin = 2.000000,
	 	 xmax = 5.000000,
	 	 ymin = -130.000000,
	 	 ymax = -80.000000,
	 	 xlabel = {Range in m},
	 	 ylabel = {norm. power in dB},
	 	 colorbar,
	 	 colormap name=viridis,
	 	 colorbar style = {%,
	 	 	 ylabel = {},
	 	 },
	 	 point meta min = -120.000000,
	 	 point meta max = -80.000000,
	 ]
	 	 \addplot graphics
	 	 	 [xmin=2.000000, xmax=5.000000, ymin=-130.000000, ymax=-80.000000]
	 	 {TransBottom.png};

	 	 \addplot+[%
	 	 	 % mark=*, % x, +, o
	 	 	 % % only marks
	 	 ]
	 	 table[col sep = comma]{TransBottom-plot-1.csv};

	 \end{axis}
\end{tikzpicture}
```

Image to export:
![grafik](https://user-images.githubusercontent.com/39801601/40786638-cb4f7efe-64eb-11e8-833e-2d2f647b781c.png)

Resulting png:
![grafik](https://user-images.githubusercontent.com/39801601/40786668-e01b14ce-64eb-11e8-8456-a44722c4513e.png)

Final tikz-picture:
![grafik](https://user-images.githubusercontent.com/39801601/40786692-f3fb5788-64eb-11e8-83e9-fe5344a41b75.png)

**Comment by Fiech** [comment]
This is reproducable, if the max values of the plot are outside of the view and additionally mogrify trims off part of the image.

MNWE:

```
h_plotfig = figure(44)
[X,Y] = meshgrid(1:0.5:10,1:20);
Z = sin(X) + cos(Y);
surf(X,Y,Z)
axis([0.5 2.2 0 20])
zlim([-0.5 1.6])
view(0,0)
surf3tikz(gcf,'bugtest')
```

the fig

![soll](https://user-images.githubusercontent.com/7039866/40980842-b584842e-68d9-11e8-85fa-2ce8e4e90661.jpg)

produces the following tikz-pdf:

![ist](https://user-images.githubusercontent.com/7039866/40981055-51526eac-68da-11e8-999a-2220f4b23e6c.png)

**Comment by Fiech** [comment]
The solution is to extract the actual local min and max values of the visible plot data to put into the 2D-image-mapping on [line 455](https://github.com/Fiech/surf3tikz/blob/38683cc58381d042accc956601e5d4303486b60d/surf3tikz.m#L455).

To do this however, is not trivial. The problem is, that the visible data sometimes has interpolated data as edge values. Example: in the picture above, the right hand side is at 2,2, but there is no real data point representing this value within the XData, YData, or ZData values of the surf plot.

A possible solution would be to "zoom" out to the next available data point and then make map the graphic accordingly. But we'll have to see how this affects the rest of the algorithm.

**Comment by Fiech** [comment]
The approach with the next data point turned out to be too complex because of all the variables that come into play. Therefore the current fix now zooms out the view port by 10% and then places 1px points at the very edges of the view port preventing the overcropping.
